### ISSUE TITLE
location of conference is not made clear

### ISSUE THREAD

**Issue by daveloyall** [emacsconf/emacsconf2015#9]
I scrolled up and down on http://emacsconf.github.io/emacsconf2015/ for a while and searched the document for a couple keywords: "location" and "online".

I wasn't able to figure out where this is being held.

Later I looked at the "Google+ event" which specifies the location as "Google Hangouts".

(Google Hangouts doesn't work on my GNU/Linux laptop.)

But really, this issue is about the page at http://emacsconf.github.io/emacsconf2015/ .  It should clearly state at the top where/how Emacsconf2015 will be held.

**Comment by samertm** [comment]
That's a good point--up until a couple days ago we didn't have a clear idea of _where_ it would be (which is why that isn't in the doc :smile: ), but I'm 90% sure it's going to happen in SF because that's where I have the most connections, which makes it easier to find a space. We're going to have a live stream for people that can't make it, though.

Thanks for opening this, I'll update the doc.

**Comment by samertm** [comment]
Fixed: https://github.com/emacsconf/emacsconf2015/commit/62be4ec7f8dc7d5661d1a367e0d28f9de388d39b
